# Generated by Django 3.0.6 on 2020-05-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
