# Generated by Django 3.0.6 on 2020-05-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_pessoa_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
